import '../styles/global.css';

import MainProvider from '@/shared/providers/MainProvider';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
