name: My-lex CI/CD
run-name: CI/CD

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  WEB_IMAGE_NAME: ${{ github.repository }}/web
  API_IMAGE_NAME: ${{ github.repository }}/api

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      actions: 'read'
      pull-requests: 'read'

    steps:
      - uses: actions/checkout@v5
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
          filter: tree:0 # Optional, but recommended: reduce the size of the checkout with tree filtering

      - name: Use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'master'

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - run: npm run db-generate
      - run: npx nx affected -t lint test build

  build-and-push-apps-images:
    needs: build-test-lint
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Login to the registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Cache Docker layers
        uses: actions/cache@v5
        with:
          path: /tmp/.my-lex-cache
          key: ${{ runner.os }}-my-lex-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-my-lex-cache-

      # WEB IMAGE
      - name: Extract metadata for WEB IMAGE
        id: web_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.WEB_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push WEB IMAGE
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./apps/web/Dockerfile
          tags: ${{ steps.web_meta.outputs.tags }}
          labels: ${{ steps.web_meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_API_BASE_URL=${{ secrets.API_BASE_URL }}
            NEXT_PUBLIC_GOOGLE_RECAPTCHA_SITE_KEY=${{ secrets.GOOGLE_RECAPTCHA_SITE_KEY }}
          cache-from: type=local,src=/tmp/.my-lex-cache/web-cache
          cache-to: type=local,dest=/tmp/.my-lex-cache-new/web-cache,mode=max

      # API IMAGE
      - name: Extract metadata for API IMAGE
        id: api_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push API IMAGE
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./apps/api/Dockerfile
          tags: ${{ steps.api_meta.outputs.tags }}
          labels: ${{ steps.api_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.my-lex-cache/api-cache
          cache-to: type=local,dest=/tmp/.my-lex-cache-new/api-cache,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.my-lex-cache
          mv /tmp/.my-lex-cache-new /tmp/.my-lex-cache

  deploy:
    needs: build-and-push-apps-images
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v5

      - name: Upload docker compose to the server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: 'docker-compose.prod.yml'
          target: /home/${{ secrets.SERVER_USER }}/my-lex/
          overwrite: true

      - name: Connect to the server and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/my-lex
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker system prune -f
